import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
  // https://www.mercadopago.com.br/developers/panel/app/3852797968096937/credentials/sandbox
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="">
      <head />

      <body className={inter.className}>{children}</body>
    </html>
  )
}
